"""Task schemas for the writer agent pipeline."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional


@dataclass(slots=True)
class PlanDirective:
    """High-level instructions generated by the planner agent."""

    objective: str
    deliverable_format: str
    tone: str
    style_constraints: List[str] = field(default_factory=list)
    citation_expectations: str = "Cite Bayesian nodes using [Node:Outcome] notation."

    def to_prompt(self) -> str:
        """Render the directive as a prompt segment."""
        lines = [f"Objective: {self.objective}", f"Deliverable: {self.deliverable_format}", f"Tone: {self.tone}"]
        if self.style_constraints:
            lines.append("Constraints:")
            lines.extend(f"- {constraint}" for constraint in self.style_constraints)
        lines.append(f"Citations: {self.citation_expectations}")
        return "\n".join(lines)


@dataclass(slots=True)
class SectionPlan:
    """Detailed section specification derived from the planner agent."""

    section_id: str
    title: str
    objective: str
    key_points: List[str]
    idiom_tags: List[str] = field(default_factory=list)
    tone: Optional[str] = None
    evidence_refs: List[str] = field(default_factory=list)

    def to_prompt(self) -> str:
        """Render section plan as instructions for the writer agent."""
        lines = [f"Section: {self.title}", f"Objective: {self.objective}"]
        if self.tone:
            lines.append(f"Tone: {self.tone}")
        if self.key_points:
            lines.append("Key Points:")
            lines.extend(f"- {point}" for point in self.key_points)
        if self.idiom_tags:
            lines.append(f"Idiom Tags: {', '.join(self.idiom_tags)}")
        if self.evidence_refs:
            lines.append("Citations:")
            lines.extend(f"- {ref}" for ref in self.evidence_refs)
        return "\n".join(lines)


@dataclass(slots=True)
class DraftSection:
    """Section content returned by the writer agent."""

    section_id: str
    title: str
    body: str


@dataclass(slots=True)
class ReviewFindings:
    """Issues discovered by the double checker or editor."""

    section_id: Optional[str]
    severity: str
    message: str
    suggestions: Optional[str] = None


@dataclass(slots=True)
class WriterDeliverable:
    """Final output produced by the orchestration pipeline."""

    plan: PlanDirective
    sections: List[DraftSection]
    edited_document: str
    reviews: List[ReviewFindings] = field(default_factory=list)
    metadata: Dict[str, str] = field(default_factory=dict)


__all__ = [
    "PlanDirective",
    "SectionPlan",
    "DraftSection",
    "ReviewFindings",
    "WriterDeliverable",
]
