"""View recent insights generated by background agents."""

import json
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


def format_timestamp(ts_str: str) -> str:
    """Format ISO timestamp for display."""
    try:
        dt = datetime.fromisoformat(ts_str)
        return dt.strftime("%Y-%m-%d %H:%M:%S")
    except:
        return ts_str


def view_document_analysis(limit: int = 5):
    """View recent document analyses."""
    output_dir = Path("background_agents/outputs/document_analysis")

    if not output_dir.exists():
        return

    files = sorted(output_dir.glob("*.json"), key=lambda f: f.stat().st_mtime, reverse=True)

    if not files:
        return

    print("\n📄 Recent Document Analyses")
    print("   " + "="*55)

    for file in files[:limit]:
        try:
            with open(file) as f:
                data = json.load(f)

            print(f"\n   File: {data.get('file_name', 'Unknown')}")
            print(f"   Processed: {format_timestamp(data.get('processed_at', ''))}")

            extracted = data.get('extracted_data', {})
            if 'case_name' in extracted:
                print(f"   Case: {extracted['case_name']}")
            if 'document_type' in extracted:
                print(f"   Type: {extracted['document_type']}")

        except Exception as e:
            print(f"   ⚠️  Error reading {file.name}: {e}")


def view_research_insights(limit: int = 3):
    """View recent research insights."""
    summaries_dir = Path("background_agents/outputs/research/case_summaries")

    if not summaries_dir.exists():
        return

    files = sorted(summaries_dir.glob("*.md"), key=lambda f: f.stat().st_mtime, reverse=True)

    if not files:
        return

    print("\n\n🔍 Recent Research Insights")
    print("   " + "="*55)

    for file in files[:limit]:
        try:
            with open(file) as f:
                content = f.read()

            # Extract first few lines
            lines = content.split('\n')
            header = '\n'.join(lines[:8])

            print(f"\n   {file.name}")
            print("   " + "-"*55)
            for line in header.split('\n')[:4]:
                if line.strip():
                    print(f"   {line}")

        except Exception as e:
            print(f"   ⚠️  Error reading {file.name}: {e}")


def view_patterns(limit: int = 2):
    """View recent pattern analyses."""
    patterns_dir = Path("background_agents/outputs/patterns")

    if not patterns_dir.exists():
        return

    files = sorted(patterns_dir.glob("*.json"), key=lambda f: f.stat().st_mtime, reverse=True)

    if not files:
        return

    print("\n\n🔍 Recent Pattern Analyses")
    print("   " + "="*55)

    for file in files[:limit]:
        try:
            with open(file) as f:
                data = json.load(f)

            print(f"\n   Analysis: {file.stem}")
            print(f"   Timestamp: {format_timestamp(data.get('timestamp', ''))}")
            print(f"   Cases Analyzed: {data.get('cases_analyzed', 0)}")

            patterns = data.get('patterns', {})
            if isinstance(patterns, dict) and 'success_factors' in patterns:
                print(f"   Success Factors Found: Yes")

        except Exception as e:
            print(f"   ⚠️  Error reading {file.name}: {e}")


def view_settlements(limit: int = 2):
    """View recent settlement analyses."""
    settlements_dir = Path("background_agents/outputs/settlements")

    if not settlements_dir.exists():
        return

    files = sorted(settlements_dir.glob("*.json"), key=lambda f: f.stat().st_mtime, reverse=True)

    if not files:
        return

    print("\n\n💰 Recent Settlement Analyses")
    print("   " + "="*55)

    for file in files[:limit]:
        try:
            with open(file) as f:
                data = json.load(f)

            params = data.get('parameters', {})
            optimal = data.get('optimal_settlement', {})

            print(f"\n   Case: {file.stem.replace('settlement_', '')}")
            print(f"   Timestamp: {format_timestamp(data.get('timestamp', ''))}")
            print(f"   Success Probability: {params.get('success_probability', 0):.1%}")
            print(f"   Expected Value: ${params.get('damages_mean', 0):,.0f}")
            print(f"   Optimal Settlement: ${optimal.get('optimal_settlement', 0):,.0f}")

        except Exception as e:
            print(f"   ⚠️  Error reading {file.name}: {e}")


def main():
    """Main entry point."""
    import argparse

    parser = argparse.ArgumentParser(description="View background agent insights")
    parser.add_argument('--recent', type=int, default=5, help='Number of recent items to show')

    args = parser.parse_args()

    print("\n" + "="*60)
    print("💡 Background Agent Insights")
    print("="*60)

    # Check if outputs exist
    outputs_dir = Path("background_agents/outputs")
    if not outputs_dir.exists():
        print("\n❌ No outputs found yet")
        print("   The system may not have processed any tasks yet.")
        print("   Check back after the agents have been running for a while.")
        return

    # View different types of insights
    view_document_analysis(args.recent)
    view_research_insights(args.recent)
    view_patterns(args.recent)
    view_settlements(args.recent)

    print("\n" + "="*60)
    print("\n💡 Tip: Full outputs are available in background_agents/outputs/")
    print()


if __name__ == "__main__":
    main()

